# Docker Compose file for taskd server
# @author Daniel Yuan (danielyuan.me)
version: '3'
services:
  taskd:
    build:
      context: .
      args:
        - GID=53589
        - UID=53589
        - USER=taskd-service
    ports:
      - 53589:53589
    volumes:
      - ./taskd:/app/taskd
      - ./var:/var/taskd
    environment:
      - TASKDDATA=/var/taskd
      - TASKDCN=0.0.0.0
    restart_policy:
      condition: any
